version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    volumes:
      - ./backend:/var/www
    ports:
      - 8000:8000
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: vue_app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    networks:
      - app-network

# Bỏ nginx nếu bạn đang dev mode
# Nếu bạn vẫn muốn dùng nginx reverse proxy, cần config lại cho phù hợp với cổng dev
# Hoặc dùng khi đã build frontend ra `dist`

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
