version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    volumes:
      - ./backend:/var/www
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network
      
  queue:
    build:
      context: ./backend
    container_name: queue_worker
    command: php artisan queue:work --tries=3 --timeout=60
    volumes:
      - ./backend:/var/www
    depends_on:
      - app
      - redis
    networks:
      - app-network

  scheduler:
    build:
      context: ./backend
    container_name: laravel_scheduler
    command: sh -c "while [ true ]; do php artisan schedule:run --verbose --no-interaction & sleep 60; done"
    volumes:
      - ./backend:/var/www
    depends_on:
      - app
    networks:
      - app-network


  redis: 
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - app-network
  
  

  frontend:
    build:
      context: ./frontend
    container_name: vue_app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
